# Generated by Django 5.1.1 on 2024-11-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('birthday', models.DateTimeField(default=None)),
                ('degree', models.CharField(max_length=30)),
                ('experience', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('freelance', models.IntegerField(choices=[(0, 'Available'), (1, 'Unavailable')], default=0)),
                ('text', models.TextField()),
            ],
        ),
    ]
