# Generated by Django 5.1.1 on 2024-11-02 23:02

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_in', models.CharField(max_length=50)),
                ('University', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=30)),
                ('text', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='freelance',
            field=models.CharField(choices=[('Available', 'A'), ('Unavailable', 'U')], max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
