# Generated by Django 5.1.1 on 2024-11-02 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_qualification_alter_about_freelance_alter_about_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qualification',
            new_name='Education',
        ),
    ]
