# Generated by Django 5.1.1 on 2024-11-03 07:30

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_expericence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=30)),
                ('icon', models.CharField(max_length=30)),
                ('text', tinymce.models.HTMLField()),
            ],
        ),
    ]
