# Generated by Django 5.1.1 on 2024-11-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='photo_me',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
