# Generated by Django 5.1.1 on 2024-11-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_about_photo_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
        ),
    ]
