# Generated by Django 5.1.1 on 2024-11-03 12:07

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('client_image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('client_message', tinymce.models.HTMLField()),
            ],
        ),
    ]
