# Generated by Django 5.1.1 on 2024-11-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=30)),
                ('skill_percentage', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
            ],
        ),
    ]
