# Generated by Django 5.1.1 on 2024-11-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='position',
            field=models.CharField(choices=[('first', 'f'), ('second', 's'), ('third', 't')], default='f', max_length=50),
        ),
    ]
